### ISSUE TITLE
The func library is missing many imports, some of which idk about

### ISSUE THREAD

**Issue by Ziad-ElAlaily** [keshavbansal015/Job-Description-Parser#1]
I imported the spacy library into func.py and now its asking for matcher. It needs a review over the required libraries that need to be imported

**Comment by keshavbansal015** [comment]
Hey thank you for your feedback, the project isn't structured properly as of now, I'll try to update that asap.

Regarding your query,
The spaCy_parser script actually imports func.py script, so try that way once.
The 'matcher' is just a spacy PhraseMatcher object that I actually initialized in spaCy_parser script.

**Comment by Ziad-ElAlaily** [comment]
I like your code and hope it works. The idea is when functions in func.py start running for e.g nlp, nlp is defined in spaCy_parser but not in func.py so func.py gives an error

**Comment by keshavbansal015** [comment]
Yes exactly, I'll try to improve on it. 
Thank you for your feedback :-)
